[workspace]
members = [
    "function",
    "cb",
    "promise",
    "async-cb",
    "json",
    "param",
    "js-env",
    "class-simple",
    "class-wrapper",
    "class-async",
    "stream",
]

#[patch.crates-io]
#flv-future-aio = { path = "../../flv-future/src/future-aio"}