[package]
name = "nj-cli"
version = "0.1.2"
authors = ["fluvio.io"]
edition = "2018"
description = "build tool for node-bindgen"
repository = "https://github.com/infinyon/node-bindgen"
license = "Apache-2.0"

[workspace]

[dependencies]
log = "0.4.8"
structopt = { version = "0.2.14", default-features = false }
cargo_metadata = "0.9.1"